### ISSUE TITLE
visual studio for c++ on Mac 

### ISSUE THREAD

**Issue by Lamia-21** [RahmanKhorramfar91/Cpp-Cplex-Tutorial#1]
I cannot find a way to use this tool with visual studio on Mac. Can you help me to link c++ project with cplex?

**Comment by RahmanKhorramfar91** [comment]
Hi,

Unfortunately I have never used a Mac machine before but look at this page
<https://www.ibm.com/docs/en/icos/12.9.0?topic=cplex-setting-up-gnulinuxmacos>
that might help.

-Rahman
